plugins { id 'com.android.application' }
android { namespace 'com.dadir.muslimssoulmate'; compileSdk 35
 defaultConfig { applicationId 'com.dadir.muslimssoulmate'; minSdk 26; targetSdk 35; versionCode 4; versionName '0.4.0-beta' }
 buildTypes { debug { debuggable true }; release { minifyEnabled false } }
}
