'use client';
import React,{createContext,useContext} from 'react';
export const languages=[['en','English'],['so','Soomaali'],['ar','العربية'],['ur','اردو'],['hi','हिन्दी'],['bn','বাংলা'],['fr','Français'],['es','Español'],['pt','Português'],['tr','Türkçe'],['id','Bahasa Indonesia'],['sw','Kiswahili'],['zh','中文']];
const keys=['Discover','Messages','Matchmaking','Short videos','My profile','Settings','Create my profile','Edit my profile','Real name','Age','Gender','City, country','Current marital status','Marital history','Religiosity','Sect (optional)','A little about you','Save my profile','Woman','Man','Single','Separated','Married','Never married','Divorced','Widowed','Prefer not to say','Everyone','Anywhere','All ages','Say Asc','Inquiries','Conversations','Reply','Decline','Block','Report','Send message','Write a respectful message…','Create a group','Join circle','Open group chat','Leave','Upload','Cancel','Save','Record voice message','Stop recording','Send recording','Retake','Open camera','Language','Membership','Audio call','Video call','End call','Accept call','Reject call','Meet with intention.','Your space. Your choices.','Let your story begin.','More than a profile.','A conversation can change everything.','A little help finding your person.'];
const rows:Record<string,string[]>={
so:['Soo hel','Farriimo','Isbarasho','Fiidiyowyo gaagaaban','Boggeyga','Dejinta','Samee boggeyga','Wax ka beddel boggeyga','Magaca dhabta ah','Da’da','Jinsiga','Magaalada, dalka','Xaaladda guurka hadda','Taariikhda guurka','Ku dhaqanka diinta','Madhab (ikhtiyaari)','Wax yar oo adiga kugu saabsan','Kaydi boggeyga','Haweeney','Nin','Aan guursan','Kala maqan','Guursaday','Weligii ma guursan','La furay','Laga geeriyooday','Ma doonayo inaan sheego','Dhammaan','Meel kasta','Da’ kasta','Dheh Asc','Codsiyo','Wadahadallo','Jawaab','Diid','Xannib','Soo sheeg','Dir farriinta','Qor farriin xushmad leh…','Samee koox','Ku biir kooxda','Fur wada sheekaysiga','Ka bax','Soo geli','Jooji','Kaydi','Duub farriin cod ah','Jooji duubista','Dir codka','Dib u qaad','Fur kamaradda','Luqadda','Xubinnimada','Wicitaan cod ah','Wicitaan muuqaal ah','Jooji wicitaanka','Aqbal wicitaanka','Diid wicitaanka','Ujeeddo wanaagsan ku baro qof.','Meeshaada. Doorashadaada.','Sheekadaadu ha bilaabato.','Wax ka badan bog keliya.','Wadahadal ayaa wax walba beddeli kara.','Caawimo yar oo aad ku hesho qofkaaga.'],
ar:['اكتشف','الرسائل','التوفيق للزواج','فيديوهات قصيرة','ملفي الشخصي','الإعدادات','إنشاء ملفي','تعديل ملفي','الاسم الحقيقي','العمر','الجنس','المدينة، البلد','الحالة الاجتماعية الحالية','تاريخ الزواج','التدين','المذهب (اختياري)','نبذة عنك','حفظ ملفي','امرأة','رجل','أعزب','منفصل','متزوج','لم يسبق الزواج','مطلق','أرمل','أفضل عدم الإفصاح','الجميع','أي مكان','كل الأعمار','أرسل السلام','طلبات التعارف','المحادثات','رد','رفض','حظر','إبلاغ','إرسال الرسالة','اكتب رسالة محترمة…','إنشاء مجموعة','انضم للمجموعة','فتح المحادثة الجماعية','مغادرة','رفع','إلغاء','حفظ','تسجيل رسالة صوتية','إيقاف التسجيل','إرسال التسجيل','إعادة التصوير','فتح الكاميرا','اللغة','العضوية','مكالمة صوتية','مكالمة فيديو','إنهاء المكالمة','قبول المكالمة','رفض المكالمة','تعارف بنية جادة.','مساحتك. اختياراتك.','لتبدأ قصتك.','أكثر من مجرد ملف شخصي.','محادثة قد تغير كل شيء.','مساعدة بسيطة للعثور على شريكك.'],
ur:['دریافت کریں','پیغامات','رشتہ تلاش کریں','مختصر ویڈیوز','میرا پروفائل','ترتیبات','میرا پروفائل بنائیں','پروفائل تبدیل کریں','اصل نام','عمر','جنس','شہر، ملک','موجودہ ازدواجی حیثیت','ازدواجی تاریخ','دین سے وابستگی','مسلک (اختیاری)','اپنے بارے میں','پروفائل محفوظ کریں','عورت','مرد','غیر شادی شدہ','علیحدہ','شادی شدہ','کبھی شادی نہیں ہوئی','طلاق یافتہ','بیوہ یا رنڈوا','بتانا نہیں چاہتے','سب','کہیں بھی','تمام عمریں','سلام بھیجیں','درخواستیں','گفتگو','جواب دیں','انکار','بلاک کریں','رپورٹ کریں','پیغام بھیجیں','احترام سے پیغام لکھیں…','گروپ بنائیں','گروپ میں شامل ہوں','گروپ گفتگو کھولیں','چھوڑ دیں','اپ لوڈ','منسوخ','محفوظ کریں','صوتی پیغام ریکارڈ کریں','ریکارڈنگ روکیں','ریکارڈنگ بھیجیں','دوبارہ تصویر لیں','کیمرہ کھولیں','زبان','رکنیت','آڈیو کال','ویڈیو کال','کال ختم کریں','کال قبول کریں','کال مسترد کریں','سنجیدہ نیت سے ملیں۔','آپ کی جگہ۔ آپ کا انتخاب۔','اپنی کہانی شروع کریں۔','صرف ایک پروفائل سے بڑھ کر۔','ایک گفتگو سب کچھ بدل سکتی ہے۔','اپنا ساتھی تلاش کرنے میں تھوڑی مدد۔'],
hi:['खोजें','संदेश','रिश्ता खोजें','छोटे वीडियो','मेरी प्रोफ़ाइल','सेटिंग्स','मेरी प्रोफ़ाइल बनाएँ','प्रोफ़ाइल बदलें','असली नाम','उम्र','लिंग','शहर, देश','वर्तमान वैवाहिक स्थिति','वैवाहिक इतिहास','धार्मिक आचरण','पंथ (वैकल्पिक)','अपने बारे में','प्रोफ़ाइल सहेजें','महिला','पुरुष','अविवाहित','अलग रह रहे','विवाहित','कभी विवाह नहीं हुआ','तलाकशुदा','विधवा या विधुर','बताना नहीं चाहते','सभी','कहीं भी','सभी उम्र','सलाम भेजें','अनुरोध','बातचीत','जवाब दें','अस्वीकार','ब्लॉक करें','रिपोर्ट करें','संदेश भेजें','सम्मानपूर्वक संदेश लिखें…','समूह बनाएँ','समूह से जुड़ें','समूह चैट खोलें','छोड़ें','अपलोड','रद्द करें','सहेजें','आवाज़ का संदेश रिकॉर्ड करें','रिकॉर्डिंग रोकें','रिकॉर्डिंग भेजें','फिर से लें','कैमरा खोलें','भाषा','सदस्यता','ऑडियो कॉल','वीडियो कॉल','कॉल समाप्त करें','कॉल स्वीकार करें','कॉल अस्वीकार करें','गंभीर इरादे से मिलें।','आपकी जगह। आपका चुनाव।','अपनी कहानी शुरू करें।','प्रोफ़ाइल से बढ़कर।','एक बातचीत सब कुछ बदल सकती है।','साथी खोजने में थोड़ी मदद।'],
bn:['খুঁজুন','বার্তা','জীবনসঙ্গী খোঁজা','ছোট ভিডিও','আমার প্রোফাইল','সেটিংস','প্রোফাইল তৈরি করুন','প্রোফাইল সম্পাদনা','আসল নাম','বয়স','লিঙ্গ','শহর, দেশ','বর্তমান বৈবাহিক অবস্থা','বৈবাহিক ইতিহাস','ধর্মীয় অনুশীলন','মতাদর্শ (ঐচ্ছিক)','আপনার সম্পর্কে','প্রোফাইল সংরক্ষণ','নারী','পুরুষ','অবিবাহিত','আলাদা থাকেন','বিবাহিত','কখনো বিয়ে হয়নি','তালাকপ্রাপ্ত','বিধবা বা বিপত্নীক','বলতে চাই না','সবাই','যেকোনো স্থান','সব বয়স','সালাম পাঠান','অনুরোধ','কথোপকথন','উত্তর দিন','প্রত্যাখ্যান','ব্লক করুন','রিপোর্ট করুন','বার্তা পাঠান','সম্মানজনক বার্তা লিখুন…','গ্রুপ তৈরি করুন','গ্রুপে যোগ দিন','গ্রুপ চ্যাট খুলুন','ছেড়ে যান','আপলোড','বাতিল','সংরক্ষণ','ভয়েস বার্তা রেকর্ড করুন','রেকর্ডিং থামান','রেকর্ডিং পাঠান','আবার তুলুন','ক্যামেরা খুলুন','ভাষা','সদস্যপদ','অডিও কল','ভিডিও কল','কল শেষ করুন','কল গ্রহণ করুন','কল প্রত্যাখ্যান','আন্তরিক উদ্দেশ্যে পরিচিত হন।','আপনার জায়গা। আপনার পছন্দ।','আপনার গল্প শুরু হোক।','প্রোফাইলের চেয়েও বেশি।','একটি কথোপকথন সব বদলে দিতে পারে।','জীবনসঙ্গী খুঁজতে একটু সাহায্য।'],
fr:['Découvrir','Messages','Rencontres','Vidéos courtes','Mon profil','Paramètres','Créer mon profil','Modifier mon profil','Vrai nom','Âge','Genre','Ville, pays','Situation conjugale actuelle','Parcours conjugal','Pratique religieuse','Courant (facultatif)','À propos de vous','Enregistrer mon profil','Femme','Homme','Célibataire','Séparé','Marié','Jamais marié','Divorcé','Veuf','Préfère ne pas préciser','Tout le monde','Partout','Tous les âges','Dire Asc','Demandes','Conversations','Répondre','Refuser','Bloquer','Signaler','Envoyer le message','Écrivez un message respectueux…','Créer un groupe','Rejoindre le groupe','Ouvrir la discussion','Quitter','Importer','Annuler','Enregistrer','Enregistrer un message vocal','Arrêter l’enregistrement','Envoyer l’enregistrement','Reprendre','Ouvrir la caméra','Langue','Abonnement','Appel audio','Appel vidéo','Raccrocher','Accepter l’appel','Refuser l’appel','Rencontrez avec intention.','Votre espace. Vos choix.','Que votre histoire commence.','Plus qu’un profil.','Une conversation peut tout changer.','Un peu d’aide pour trouver votre partenaire.'],
es:['Descubrir','Mensajes','Encuentros','Videos cortos','Mi perfil','Configuración','Crear mi perfil','Editar mi perfil','Nombre real','Edad','Género','Ciudad, país','Estado civil actual','Historial matrimonial','Práctica religiosa','Rama (opcional)','Acerca de ti','Guardar mi perfil','Mujer','Hombre','Soltero','Separado','Casado','Nunca casado','Divorciado','Viudo','Prefiero no decirlo','Todos','Cualquier lugar','Todas las edades','Decir Asc','Solicitudes','Conversaciones','Responder','Rechazar','Bloquear','Reportar','Enviar mensaje','Escribe un mensaje respetuoso…','Crear grupo','Unirse al grupo','Abrir chat grupal','Salir','Subir','Cancelar','Guardar','Grabar mensaje de voz','Detener grabación','Enviar grabación','Volver a tomar','Abrir cámara','Idioma','Suscripción','Llamada de audio','Videollamada','Finalizar llamada','Aceptar llamada','Rechazar llamada','Conoce con intención.','Tu espacio. Tus decisiones.','Que comience tu historia.','Más que un perfil.','Una conversación puede cambiarlo todo.','Un poco de ayuda para encontrar a tu pareja.'],
pt:['Descobrir','Mensagens','Encontros','Vídeos curtos','Meu perfil','Configurações','Criar meu perfil','Editar meu perfil','Nome verdadeiro','Idade','Gênero','Cidade, país','Estado civil atual','Histórico conjugal','Prática religiosa','Vertente (opcional)','Sobre você','Salvar meu perfil','Mulher','Homem','Solteiro','Separado','Casado','Nunca casou','Divorciado','Viúvo','Prefiro não informar','Todos','Qualquer lugar','Todas as idades','Dizer Asc','Solicitações','Conversas','Responder','Recusar','Bloquear','Denunciar','Enviar mensagem','Escreva uma mensagem respeitosa…','Criar grupo','Entrar no grupo','Abrir conversa do grupo','Sair','Enviar arquivo','Cancelar','Salvar','Gravar mensagem de voz','Parar gravação','Enviar gravação','Tirar novamente','Abrir câmera','Idioma','Assinatura','Chamada de áudio','Chamada de vídeo','Encerrar chamada','Aceitar chamada','Recusar chamada','Conheça com intenção.','Seu espaço. Suas escolhas.','Que sua história comece.','Mais que um perfil.','Uma conversa pode mudar tudo.','Uma ajuda para encontrar sua pessoa.'],
tr:['Keşfet','Mesajlar','Eşleştirme','Kısa videolar','Profilim','Ayarlar','Profilimi oluştur','Profilimi düzenle','Gerçek ad','Yaş','Cinsiyet','Şehir, ülke','Mevcut medeni durum','Evlilik geçmişi','Dini yaşam','Mezhep (isteğe bağlı)','Hakkınızda','Profilimi kaydet','Kadın','Erkek','Bekâr','Ayrı yaşıyor','Evli','Hiç evlenmedi','Boşanmış','Dul','Belirtmek istemiyorum','Herkes','Her yer','Tüm yaşlar','Selam ver','İstekler','Sohbetler','Yanıtla','Reddet','Engelle','Bildir','Mesaj gönder','Saygılı bir mesaj yazın…','Grup oluştur','Gruba katıl','Grup sohbetini aç','Ayrıl','Yükle','İptal','Kaydet','Sesli mesaj kaydet','Kaydı durdur','Kaydı gönder','Yeniden çek','Kamerayı aç','Dil','Üyelik','Sesli arama','Görüntülü arama','Aramayı bitir','Aramayı kabul et','Aramayı reddet','Ciddi niyetle tanışın.','Sizin alanınız. Sizin seçiminiz.','Hikâyeniz başlasın.','Bir profilden fazlası.','Bir sohbet her şeyi değiştirebilir.','Eşinizi bulmak için küçük bir yardım.'],
id:['Temukan','Pesan','Perjodohan','Video pendek','Profil saya','Pengaturan','Buat profil saya','Edit profil saya','Nama asli','Usia','Jenis kelamin','Kota, negara','Status perkawinan saat ini','Riwayat perkawinan','Praktik agama','Aliran (opsional)','Tentang Anda','Simpan profil saya','Perempuan','Laki-laki','Lajang','Berpisah','Menikah','Belum pernah menikah','Bercerai','Ditinggal wafat','Tidak ingin menyebutkan','Semua','Di mana saja','Semua usia','Kirim salam','Permintaan','Percakapan','Balas','Tolak','Blokir','Laporkan','Kirim pesan','Tulis pesan yang sopan…','Buat grup','Gabung grup','Buka obrolan grup','Keluar','Unggah','Batal','Simpan','Rekam pesan suara','Hentikan rekaman','Kirim rekaman','Ambil ulang','Buka kamera','Bahasa','Keanggotaan','Panggilan suara','Panggilan video','Akhiri panggilan','Terima panggilan','Tolak panggilan','Berkenalan dengan niat baik.','Ruang Anda. Pilihan Anda.','Mulailah cerita Anda.','Lebih dari sekadar profil.','Satu percakapan bisa mengubah segalanya.','Sedikit bantuan menemukan pasangan.'],
sw:['Gundua','Ujumbe','Kutafuta mwenzi','Video fupi','Wasifu wangu','Mipangilio','Unda wasifu wangu','Hariri wasifu wangu','Jina halisi','Umri','Jinsia','Mji, nchi','Hali ya ndoa sasa','Historia ya ndoa','Uchaji wa dini','Madhehebu (hiari)','Kuhusu wewe','Hifadhi wasifu','Mwanamke','Mwanamume','Hajaoa au kuolewa','Wametengana','Ameoa au kuolewa','Hajawahi kuoa au kuolewa','Ametalikiwa','Mjane','Sipendi kusema','Wote','Popote','Umri wote','Sema Asc','Maombi','Mazungumzo','Jibu','Kataa','Zuia','Ripoti','Tuma ujumbe','Andika ujumbe wa heshima…','Unda kikundi','Jiunge na kikundi','Fungua mazungumzo ya kikundi','Ondoka','Pakia','Ghairi','Hifadhi','Rekodi ujumbe wa sauti','Simamisha kurekodi','Tuma rekodi','Piga tena','Fungua kamera','Lugha','Uanachama','Simu ya sauti','Simu ya video','Maliza simu','Pokea simu','Kataa simu','Kutana kwa nia njema.','Nafasi yako. Chaguo lako.','Hadithi yako ianze.','Zaidi ya wasifu.','Mazungumzo yanaweza kubadilisha kila kitu.','Msaada kidogo kumpata mwenzi wako.'],
zh:['发现','消息','婚恋配对','短视频','我的资料','设置','创建资料','编辑资料','真实姓名','年龄','性别','城市、国家','当前婚姻状况','婚姻经历','宗教实践','教派（可选）','自我介绍','保存资料','女性','男性','单身','分居','已婚','从未结婚','离异','丧偶','不愿透露','所有人','任何地方','所有年龄','发送问候','交友请求','聊天','回复','拒绝','屏蔽','举报','发送消息','请礼貌地输入消息…','创建群组','加入群组','打开群聊','退出','上传','取消','保存','录制语音消息','停止录音','发送录音','重新拍摄','打开相机','语言','会员','语音通话','视频通话','结束通话','接听','拒接','真诚相识。','你的空间，你的选择。','让你的故事开始。','不只是个人资料。','一次交谈可能改变一切。','助你寻找人生伴侣。']};
export const LocaleContext=createContext('en');
export function tr(text:string,lang:string){if(extra[text]?.[lang])return extra[text][lang];const i=keys.indexOf(text);return i>=0&&rows[lang]?.[i]?rows[lang][i]:text;}
export function useText(){const lang=useContext(LocaleContext);return (s:string)=>tr(s,lang);}
export function translateTree(node:any,lang:string):any {if(lang==='en')return node;if(typeof node==='string')return tr(node,lang);if(Array.isArray(node))return node.map(x=>translateTree(x,lang));if(!React.isValidElement(node))return node;const props:any=node.props;if(props.translate==='no')return node;const changes:any={};for(const key of ['placeholder','aria-label','title'])if(typeof props[key]==='string')changes[key]=tr(props[key],lang);if(props.children!==undefined)changes.children=translateTree(props.children,lang);return React.cloneElement(node,changes);}

const extraKeys=['Events','Community events','Create an event','Sign up free','Get ticket','Event name','Public venue and address','Create event','Keep personal details private. Meet in public. Never send money to a new match.'];
const extraRows:Record<string,string[]>={
so:['Dhacdooyin','Kulamada bulshada','Samee kulan','Iska diiwaangeli bilaash','Hel tigidh','Magaca kulanka','Goob dadweyne iyo cinwaan','Samee kulan','Xogtaada gaarka ah ilaali. Ku kulma meel dadweyne. Lacag ha u dirin qof aad hadda baratay.'],
ar:['الفعاليات','فعاليات المجتمع','إنشاء فعالية','تسجيل مجاني','احصل على تذكرة','اسم الفعالية','المكان العام والعنوان','إنشاء الفعالية','احمِ معلوماتك الشخصية. التقِ في مكان عام. لا ترسل المال لشخص تعرفت عليه حديثًا.'],
ur:['تقریبات','کمیونٹی تقریبات','تقریب بنائیں','مفت اندراج','ٹکٹ حاصل کریں','تقریب کا نام','عوامی مقام اور پتہ','تقریب بنائیں','ذاتی معلومات محفوظ رکھیں۔ عوامی جگہ پر ملیں۔ نئے واقف شخص کو رقم نہ بھیجیں۔'],
hi:['कार्यक्रम','सामुदायिक कार्यक्रम','कार्यक्रम बनाएँ','मुफ़्त पंजीकरण','टिकट लें','कार्यक्रम का नाम','सार्वजनिक स्थान और पता','कार्यक्रम बनाएँ','निजी जानकारी सुरक्षित रखें। सार्वजनिक स्थान पर मिलें। नए परिचित को पैसे न भेजें।'],
bn:['অনুষ্ঠান','কমিউনিটি অনুষ্ঠান','অনুষ্ঠান তৈরি করুন','বিনামূল্যে নিবন্ধন','টিকিট নিন','অনুষ্ঠানের নাম','সর্বজনীন স্থান ও ঠিকানা','অনুষ্ঠান তৈরি করুন','ব্যক্তিগত তথ্য গোপন রাখুন। জনসমাগমস্থলে দেখা করুন। নতুন পরিচিত কাউকে টাকা পাঠাবেন না।'],
fr:['Événements','Événements communautaires','Créer un événement','Inscription gratuite','Obtenir un billet','Nom de l’événement','Lieu public et adresse','Créer l’événement','Protégez vos informations personnelles. Rencontrez-vous en public. N’envoyez jamais d’argent à une nouvelle connaissance.'],
es:['Eventos','Eventos de la comunidad','Crear un evento','Inscripción gratuita','Obtener entrada','Nombre del evento','Lugar público y dirección','Crear evento','Protege tus datos personales. Queda en un lugar público. Nunca envíes dinero a alguien que acabas de conocer.'],
pt:['Eventos','Eventos da comunidade','Criar um evento','Inscrição gratuita','Obter ingresso','Nome do evento','Local público e endereço','Criar evento','Proteja seus dados pessoais. Encontre-se em público. Nunca envie dinheiro a alguém que acabou de conhecer.'],
tr:['Etkinlikler','Topluluk etkinlikleri','Etkinlik oluştur','Ücretsiz kayıt','Bilet al','Etkinlik adı','Halka açık mekân ve adres','Etkinlik oluştur','Kişisel bilgilerinizi koruyun. Halka açık bir yerde buluşun. Yeni tanıştığınız kişiye para göndermeyin.'],
id:['Acara','Acara komunitas','Buat acara','Daftar gratis','Dapatkan tiket','Nama acara','Tempat umum dan alamat','Buat acara','Jaga informasi pribadi. Bertemulah di tempat umum. Jangan mengirim uang kepada orang yang baru dikenal.'],
sw:['Matukio','Matukio ya jamii','Unda tukio','Jisajili bila malipo','Pata tiketi','Jina la tukio','Mahali pa umma na anwani','Unda tukio','Linda taarifa binafsi. Kutana mahali pa umma. Usimtumie pesa mtu uliyemfahamu karibuni.'],
zh:['活动','社区活动','创建活动','免费报名','获取门票','活动名称','公共场所及地址','创建活动','保护个人信息。在公共场所见面。不要向刚认识的人转账。']};
const extra:Record<string,Record<string,string>>=Object.fromEntries(extraKeys.map((key,i)=>[key,Object.fromEntries(Object.entries(extraRows).map(([lang,row])=>[lang,row[i]]))]));
export function Localized({children}:{children:React.ReactNode}){const lang=useContext(LocaleContext);return translateTree(children,lang);}
