'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,RotateCcw} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
export default function ProfileCamera({slot,onSaved}:{slot:string,onSaved:()=>void}){const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),generation=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null);const [ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(''),[blob,setBlob]=useState<Blob|null>(null),[token,setToken]=useState(''),[facing,setFacing]=useState('user'),[brightness,setBrightness]=useState(100),[contrast,setContrast]=useState(100),[count,setCount]=useState(0);const filter=`brightness(${brightness}%) contrast(${contrast}%)`;
function stop(){generation.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(timer.current)clearTimeout(timer.current);setReady(false);setCount(0);}
useEffect(()=>()=>{generation.current++;stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);},[]);
useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
async function start(direction=facing){stop();const gen=generation.current;setError('');setPreview('');setBlob(null);setToken('');try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera access is unavailable. Open this app in a supported browser using HTTPS.');const media=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:direction},width:{ideal:1440},height:{ideal:1920}}});if(gen!==generation.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;if(video.current){video.current.srcObject=media;await video.current.play();}const r=await fetch('/api/camera',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slot})});const result:any=await r.json();if(gen!==generation.current)return;if(!r.ok)throw Error(result.error);setToken(result.token);setReady(true);}catch(e:any){if(gen!==generation.current)return;stop();setError(e.name==='NotAllowedError'?'Camera permission was denied. Allow camera access in your device settings, then try again.':e.message||'Camera could not start.');}}
function capture(){if(!video.current||!stream.current?.active)return;const v=video.current;if(!v.videoWidth||!v.videoHeight){setError('Wait for the camera image, then try again.');return;}const canvas=document.createElement('canvas');const ratio=Math.min(1,1600/Math.max(v.videoWidth,v.videoHeight));canvas.width=Math.round(v.videoWidth*ratio);canvas.height=Math.round(v.videoHeight*ratio);const ctx=canvas.getContext('2d');if(!ctx)return;ctx.drawImage(v,0,0,canvas.width,canvas.height);const image=ctx.getImageData(0,0,canvas.width,canvas.height),pixels=image.data;for(let i=0;i<pixels.length;i+=4)for(let c=0;c<3;c++)pixels[i+c]=Math.min(255,Math.max(0,((pixels[i+c]*brightness/100)-128)*contrast/100+128));ctx.putImageData(image,0,0);canvas.toBlob(b=>{if(b){setBlob(b);setPreview(URL.createObjectURL(b));stop();}},'image/jpeg',.9);}
function delayedCapture(){const gen=generation.current;let n=5;setCount(n);const tick=()=>{if(gen!==generation.current)return;n--;setCount(n);if(n===0)capture();else timer.current=setTimeout(tick,1000);};timer.current=setTimeout(tick,1000);}
async function save(){if(!blob||!token)return;setBusy(true);setError('');try{const f=new FormData();f.set('capture',blob,'camera.jpg');f.set('token',token);const r=await fetch('/api/camera',{method:'POST',body:f});const d:any=await r.json();if(!r.ok)throw Error(d.error);onSaved();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
return <div className="stack"><p>{slot==='portrait'?'Take a clear portrait with your full face visible.':'Place your phone securely or ask someone to hold it. Stand back so your whole body, including your head and feet, is visible.'}</p><div className="camera-frame">{preview?<img src={preview} alt="Review your new camera photo"/>:<video ref={video} autoPlay playsInline muted style={{filter}}/>}{count>0&&<strong className="camera-count">{count}</strong>}</div>{error&&<p className="error-box" role="alert">{error}</p>}{!preview&&<><label>Brightness · {brightness}%<Slider aria-label="Brightness" value={[brightness]} onValueChange={v=>setBrightness(v[0])} min={90} max={110} step={1}/></label><label>Contrast · {contrast}%<Slider aria-label="Contrast" value={[contrast]} onValueChange={v=>setContrast(v[0])} min={90} max={110} step={1}/></label><p className="helper">Small lighting adjustments only. No skin smoothing, facial reshaping, body changes, or photo imports.</p><div className="actions">{!ready?<button className="primary" onClick={()=>start()}><Camera size={18}/>Open camera</button>:<><button className="primary" disabled={count>0} onClick={slot==='full-body'?delayedCapture:capture}>{slot==='full-body'?'Take photo · 5-second timer':'Take portrait'}</button><button className="outline" disabled={count>0} onClick={()=>{const f=facing==='user'?'environment':'user';setFacing(f);start(f);}}><RotateCcw size={17}/>Switch camera</button></>}</div></>}{preview&&<div className="actions"><button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Use this photo'}</button><button className="outline" disabled={busy} onClick={()=>start()}>Retake</button></div>}<p className="helper">Expires six calendar months after capture. Public-beta photos become visible immediately after both required captures; production launch will require moderation. Camera capture alone does not verify identity or prevent a person photographing an old image.</p></div>}
