package com.dadir.muslimssoulmate;
import android.app.*;import android.os.*;import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.view.*;import android.webkit.*;import android.widget.*;
public class MainActivity extends Activity {
 private static final String URL="https://muslims-soulmate.ayhusse1.chatgpt.site";
 private static final String HOST="muslims-soulmate.ayhusse1.chatgpt.site";
 private WebView web; private PermissionRequest camera; private GeolocationPermissions.Callback geo; private String geoOrigin; private ValueCallback<Uri[]> chooser; private TextView status; private String alertLanguage="en";
 private boolean trusted(Uri uri){return uri!=null&&"https".equals(uri.getScheme())&&HOST.equals(uri.getHost())&&(uri.getPort()==-1||uri.getPort()==443);}
 private void browser(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){Toast.makeText(this,"Install a web browser to continue.",Toast.LENGTH_LONG).show();}}
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(0xff56335f);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xfffcfbfd);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});
 LinearLayout bar=new LinearLayout(this);status=new TextView(this);status.setText("Muslims Soulmate · Beta");status.setTextColor(0xff56335f);status.setTextSize(16);status.setPadding(18,10,4,10);bar.addView(status,new LinearLayout.LayoutParams(0,-2,1));Button reload=new Button(this);reload.setText("Reload");reload.setOnClickListener(v->web.reload());bar.addView(reload);Button open=new Button(this);open.setText("Browser");open.setOnClickListener(v->browser(URL));bar.addView(open);root.addView(bar);
 web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setGeolocationEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(true);s.setUserAgentString(s.getUserAgentString()+" SoulmateAndroid/3");s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setMediaPlaybackRequiresUserGesture(true);CookieManager.getInstance().setAcceptCookie(true);
 web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest r){Uri uri=r.getUrl();if("soulmate".equals(uri.getScheme())&&"notifications".equals(uri.getHost())&&trusted(Uri.parse(web.getUrl()==null?"":web.getUrl()))){if("/disable".equals(uri.getPath())){stopService(new Intent(MainActivity.this,NotificationService.class));Toast.makeText(MainActivity.this,"Background alerts turned off",Toast.LENGTH_SHORT).show();}else if("/enable".equals(uri.getPath())){String lang=uri.getQueryParameter("lang");alertLanguage=lang!=null&&lang.matches("[a-z]{2}")?lang:"en";new AlertDialog.Builder(MainActivity.this).setTitle("Enable live notifications?").setMessage("Keep a notification connection active while this app is in the background. Android displays an ongoing notification. Battery restrictions may delay alerts.").setNegativeButton("Cancel",null).setPositiveButton("Enable",(dialog,which)->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},20);else startAlerts();}).show();}return true;}if(trusted(uri))return false;if("https".equals(uri.getScheme())){String host=uri.getHost();if("chatgpt.com".equals(host)||"auth.openai.com".equals(host)||"auth0.openai.com".equals(host))return false;browser(uri.toString());}return true;}
 @Override public void onReceivedError(WebView view,WebResourceRequest req,WebResourceError error){if(req.isForMainFrame())status.setText("Connection unavailable · Retry or open Browser");}
 @Override public void onPageFinished(WebView view,String url){status.setText("Muslims Soulmate · Beta");}});
 web.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(PermissionRequest request){runOnUiThread(()->{if(!trusted(request.getOrigin())||!trusted(Uri.parse(web.getUrl()==null?"":web.getUrl()))){request.deny();return;}java.util.ArrayList<String> permissions=new java.util.ArrayList<>();for(String resource:request.getResources()){if(PermissionRequest.RESOURCE_VIDEO_CAPTURE.equals(resource)&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.CAMERA);if(PermissionRequest.RESOURCE_AUDIO_CAPTURE.equals(resource)&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.RECORD_AUDIO);}if(permissions.isEmpty()){grantMedia(request);}else{if(camera!=null)camera.deny();camera=request;requestPermissions(permissions.toArray(new String[0]),10);}});}
 @Override public void onPermissionRequestCanceled(PermissionRequest request){if(camera==request)camera=null;}
 @Override public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback callback){if(!trusted(Uri.parse(origin))||!trusted(Uri.parse(web.getUrl()==null?"":web.getUrl()))){callback.invoke(origin,false,false);return;}if(checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED){callback.invoke(origin,true,false);}else{if(geo!=null)geo.invoke(geoOrigin,false,false);geo=callback;geoOrigin=origin;requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION,Manifest.permission.ACCESS_FINE_LOCATION},11);}}
 @Override public void onGeolocationPermissionsHidePrompt(){geo=null;geoOrigin=null;}
 @Override public boolean onShowFileChooser(WebView view,ValueCallback<Uri[]> callback,FileChooserParams params){if(!trusted(Uri.parse(web.getUrl()==null?"":web.getUrl())))return false;if(chooser!=null)chooser.onReceiveValue(null);chooser=callback;try{Intent intent=params.createIntent();intent.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(intent,12);}catch(Exception e){chooser.onReceiveValue(null);chooser=null;}return true;}});
 if(state!=null)web.restoreState(state);else web.loadUrl(URL);
 }
 @Override public void onRequestPermissionsResult(int code,String[] permissions,int[] results){super.onRequestPermissionsResult(code,permissions,results);boolean valid=trusted(Uri.parse(web.getUrl()==null?"":web.getUrl()));if(code==20){if(Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED)startAlerts();}if(code==10&&camera!=null){if(valid)grantMedia(camera);else camera.deny();camera=null;}if(code==11&&geo!=null){geo.invoke(geoOrigin,valid&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED,false);geo=null;geoOrigin=null;}}
 private void startAlerts(){Intent intent=new Intent(this,NotificationService.class);intent.putExtra("language",alertLanguage);startForegroundService(intent);}
 private void grantMedia(PermissionRequest request){java.util.ArrayList<String> resources=new java.util.ArrayList<>();for(String resource:request.getResources()){if(PermissionRequest.RESOURCE_VIDEO_CAPTURE.equals(resource)&&checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)resources.add(resource);if(PermissionRequest.RESOURCE_AUDIO_CAPTURE.equals(resource)&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)resources.add(resource);}if(resources.isEmpty())request.deny();else request.grant(resources.toArray(new String[0]));}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==12&&chooser!=null){chooser.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(result,data));chooser=null;}}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
 @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);web.saveState(out);}
 @Override protected void onPause(){super.onPause();web.evaluateJavascript("document.querySelectorAll('video').forEach(v=>{if(v.srcObject&&v.srcObject.getTracks)v.srcObject.getTracks().forEach(t=>t.stop())})",null);web.onPause();}
 @Override protected void onResume(){super.onResume();if(web!=null)web.onResume();}
 @Override protected void onDestroy(){if(camera!=null)camera.deny();if(geo!=null)geo.invoke(geoOrigin,false,false);if(chooser!=null)chooser.onReceiveValue(null);web.destroy();super.onDestroy();}
}
