package com.dadir.muslimssoulmate;
import android.app.*;import android.os.*;import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.webkit.*;import android.widget.*;import org.json.JSONObject;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;
public class MainActivity extends Activity {
 private static final String URL="https://muslims-soulmate.ayhusse1.chatgpt.site";
 private static final String HOST="muslims-soulmate.ayhusse1.chatgpt.site";
 private static final String UPDATE_URL="https://raw.githubusercontent.com/ahusseinurg/Muslims-Soulmate/main/downloads/update.json";
 private WebView web; private PermissionRequest camera; private GeolocationPermissions.Callback geo; private String geoOrigin; private ValueCallback<Uri[]> chooser; private TextView status; private String alertLanguage="en";
 private long updateDownloadId=-1;
 private final BroadcastReceiver updateReceiver=new BroadcastReceiver(){@Override public void onReceive(Context context,Intent intent){long id=intent.getLongExtra(DownloadManager.EXTRA_DOWNLOAD_ID,-1);if(id==updateDownloadId)openDownloadedUpdate();}};
 private boolean trusted(Uri uri){return uri!=null&&"https".equals(uri.getScheme())&&HOST.equals(uri.getHost())&&(uri.getPort()==-1||uri.getPort()==443);}
 private void browser(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){Toast.makeText(this,"Install a web browser to continue.",Toast.LENGTH_LONG).show();}}
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(0xff56335f);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xfffcfbfd);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});
 LinearLayout bar=new LinearLayout(this);status=new TextView(this);status.setText("Muslims Soulmate · Beta");status.setTextColor(0xff56335f);status.setTextSize(16);status.setPadding(18,10,4,10);bar.addView(status,new LinearLayout.LayoutParams(0,-2,1));Button reload=new Button(this);reload.setText("Reload");reload.setOnClickListener(v->web.reload());bar.addView(reload);Button open=new Button(this);open.setText("Browser");open.setOnClickListener(v->browser(URL));bar.addView(open);root.addView(bar);
 web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setGeolocationEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(true);s.setUserAgentString(s.getUserAgentString()+" SoulmateAndroid/4");s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setMediaPlaybackRequiresUserGesture(true);android.webkit.CookieManager.getInstance().setAcceptCookie(true);
 web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest r){Uri uri=r.getUrl();if("soulmate".equals(uri.getScheme())&&"notifications".equals(uri.getHost())&&trusted(Uri.parse(web.getUrl()==null?"":web.getUrl()))){if("/disable".equals(uri.getPath())){stopService(new Intent(MainActivity.this,NotificationService.class));Toast.makeText(MainActivity.this,"Background alerts turned off",Toast.LENGTH_SHORT).show();}else if("/enable".equals(uri.getPath())){String lang=uri.getQueryParameter("lang");alertLanguage=lang!=null&&lang.matches("[a-z]{2}")?lang:"en";new AlertDialog.Builder(MainActivity.this).setTitle("Enable live notifications?").setMessage("Keep a notification connection active while this app is in the background. Android displays an ongoing notification. Battery restrictions may delay alerts.").setNegativeButton("Cancel",null).setPositiveButton("Enable",(dialog,which)->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},20);else startAlerts();}).show();}return true;}if(trusted(uri))return false;if("https".equals(uri.getScheme())){String host=uri.getHost();if("chatgpt.com".equals(host)||"auth.openai.com".equals(host)||"auth0.openai.com".equals(host))return false;browser(uri.toString());}return true;}
 @Override public void onReceivedError(WebView view,WebResourceRequest req,WebResourceError error){if(req.isForMainFrame())status.setText("Connection unavailable · Retry or open Browser");}
 @Override public void onPageFinished(WebView view,String url){status.setText("Muslims Soulmate · Beta");}});
 web.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(PermissionRequest request){runOnUiThread(()->{if(!trusted(request.getOrigin())||!trusted(Uri.parse(web.getUrl()==null?"":web.getUrl()))){request.deny();return;}java.util.ArrayList<String> permissions=new java.util.ArrayList<>();for(String resource:request.getResources()){if(PermissionRequest.RESOURCE_VIDEO_CAPTURE.equals(resource)&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.CAMERA);if(PermissionRequest.RESOURCE_AUDIO_CAPTURE.equals(resource)&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.RECORD_AUDIO);}if(permissions.isEmpty()){grantMedia(request);}else{if(camera!=null)camera.deny();camera=request;requestPermissions(permissions.toArray(new String[0]),10);}});}
 @Override public void onPermissionRequestCanceled(PermissionRequest request){if(camera==request)camera=null;}
 @Override public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback callback){if(!trusted(Uri.parse(origin))||!trusted(Uri.parse(web.getUrl()==null?"":web.getUrl()))){callback.invoke(origin,false,false);return;}if(checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED){callback.invoke(origin,true,false);}else{if(geo!=null)geo.invoke(geoOrigin,false,false);geo=callback;geoOrigin=origin;requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION,Manifest.permission.ACCESS_FINE_LOCATION},11);}}
 @Override public void onGeolocationPermissionsHidePrompt(){geo=null;geoOrigin=null;}
 @Override public boolean onShowFileChooser(WebView view,ValueCallback<Uri[]> callback,FileChooserParams params){if(!trusted(Uri.parse(web.getUrl()==null?"":web.getUrl())))return false;if(chooser!=null)chooser.onReceiveValue(null);chooser=callback;try{Intent intent=params.createIntent();intent.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(intent,12);}catch(Exception e){chooser.onReceiveValue(null);chooser=null;}return true;}});
 if(Build.VERSION.SDK_INT>=33)registerReceiver(updateReceiver,new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE),Context.RECEIVER_NOT_EXPORTED);else registerReceiver(updateReceiver,new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE));
 if(state!=null)web.restoreState(state);else web.loadUrl(URL);checkForUpdate();
 }
 private void checkForUpdate(){new Thread(()->{try{HttpURLConnection connection=(HttpURLConnection)new URL(UPDATE_URL).openConnection();connection.setConnectTimeout(8000);connection.setReadTimeout(8000);connection.setRequestProperty("Cache-Control","no-cache");try(InputStream input=connection.getInputStream();ByteArrayOutputStream output=new ByteArrayOutputStream()){byte[] buffer=new byte[4096];int count;while((count=input.read(buffer))!=-1)output.write(buffer,0,count);JSONObject data=new JSONObject(output.toString(StandardCharsets.UTF_8.name()));int newest=data.getInt("version_code");String name=data.optString("version_name","New version");String apk=data.getString("apk_url");if(newest>getPackageManager().getPackageInfo(getPackageName(),0).versionCode)runOnUiThread(()->showUpdatePrompt(name,apk));}}catch(Exception ignored){}}).start();}
 private void showUpdatePrompt(String version,String apk){if(isFinishing())return;new AlertDialog.Builder(this).setTitle("Muslims Soulmate update available").setMessage("Version "+version+" is ready. Download it now? Android will ask you to approve installation.").setNegativeButton("Later",null).setPositiveButton("Update",(dialog,which)->downloadUpdate(apk)).show();}
 private void downloadUpdate(String apk){try{DownloadManager.Request request=new DownloadManager.Request(Uri.parse(apk));request.setTitle("Muslims Soulmate update");request.setDescription("Downloading the latest beta");request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);request.setMimeType("application/vnd.android.package-archive");request.setDestinationInExternalFilesDir(this,Environment.DIRECTORY_DOWNLOADS,"Muslims-Soulmate-update.apk");updateDownloadId=((DownloadManager)getSystemService(DOWNLOAD_SERVICE)).enqueue(request);Toast.makeText(this,"Update downloading",Toast.LENGTH_SHORT).show();}catch(Exception e){browser(apk);}}
 private void openDownloadedUpdate(){DownloadManager manager=(DownloadManager)getSystemService(DOWNLOAD_SERVICE);Uri apk=manager.getUriForDownloadedFile(updateDownloadId);if(apk==null){Toast.makeText(this,"Update download failed",Toast.LENGTH_LONG).show();return;}if(Build.VERSION.SDK_INT>=26&&!getPackageManager().canRequestPackageInstalls()){new AlertDialog.Builder(this).setTitle("Allow app updates").setMessage("Allow Muslims Soulmate to install this update, then return and tap the completed download notification.").setPositiveButton("Open settings",(d,w)->startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+getPackageName())))).setNegativeButton("Cancel",null).show();return;}Intent install=new Intent(Intent.ACTION_VIEW);install.setDataAndType(apk,"application/vnd.android.package-archive");install.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_ACTIVITY_NEW_TASK);startActivity(install);}
 @Override public void onRequestPermissionsResult(int code,String[] permissions,int[] results){super.onRequestPermissionsResult(code,permissions,results);boolean valid=trusted(Uri.parse(web.getUrl()==null?"":web.getUrl()));if(code==20){if(Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED)startAlerts();}if(code==10&&camera!=null){if(valid)grantMedia(camera);else camera.deny();camera=null;}if(code==11&&geo!=null){geo.invoke(geoOrigin,valid&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED,false);geo=null;geoOrigin=null;}}
 private void startAlerts(){Intent intent=new Intent(this,NotificationService.class);intent.putExtra("language",alertLanguage);startForegroundService(intent);}
 private void grantMedia(PermissionRequest request){java.util.ArrayList<String> resources=new java.util.ArrayList<>();for(String resource:request.getResources()){if(PermissionRequest.RESOURCE_VIDEO_CAPTURE.equals(resource)&&checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)resources.add(resource);if(PermissionRequest.RESOURCE_AUDIO_CAPTURE.equals(resource)&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)resources.add(resource);}if(resources.isEmpty())request.deny();else request.grant(resources.toArray(new String[0]));}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==12&&chooser!=null){chooser.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(result,data));chooser=null;}}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
 @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);web.saveState(out);}
 @Override protected void onPause(){super.onPause();web.evaluateJavascript("document.querySelectorAll('video').forEach(v=>{if(v.srcObject&&v.srcObject.getTracks)v.srcObject.getTracks().forEach(t=>t.stop())})",null);web.onPause();}
 @Override protected void onResume(){super.onResume();if(web!=null)web.onResume();}
 @Override protected void onDestroy(){try{unregisterReceiver(updateReceiver);}catch(Exception ignored){}if(camera!=null)camera.deny();if(geo!=null)geo.invoke(geoOrigin,false,false);if(chooser!=null)chooser.onReceiveValue(null);web.destroy();super.onDestroy();}
}
