package com.dadir.muslimssoulmate;
import android.app.*;import android.os.*;import android.content.*;import android.webkit.CookieManager;import org.json.JSONObject;import javax.net.ssl.HttpsURLConnection;import java.net.URL;import java.io.*;
public class NotificationService extends Service {
 private volatile boolean running=false;private volatile HttpsURLConnection connection;private Thread worker;private String language="en";private static final String SITE="https://muslims-soulmate.ayhusse1.chatgpt.site";
 @Override public IBinder onBind(Intent intent){return null;}
 @Override public int onStartCommand(Intent intent,int flags,int startId){if(intent!=null&&"stop".equals(intent.getAction())){stopSelf();return START_NOT_STICKY;}if(intent!=null){language=intent.getStringExtra("language")==null?"en":intent.getStringExtra("language");getSharedPreferences("alerts",MODE_PRIVATE).edit().putString("language",language).apply();}else language=getSharedPreferences("alerts",MODE_PRIVATE).getString("language","en");NotificationManager manager=getSystemService(NotificationManager.class);manager.createNotificationChannel(new NotificationChannel("soulmate_connection","Live notification connection",NotificationManager.IMPORTANCE_LOW));manager.createNotificationChannel(new NotificationChannel("soulmate_messages","Messages and calls",NotificationManager.IMPORTANCE_DEFAULT));PendingIntent stop=PendingIntent.getService(this,0,new Intent(this,NotificationService.class).setAction("stop"),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification notice=new Notification.Builder(this,"soulmate_connection").setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle("Muslims Soulmate").setContentText("Live alerts enabled · Tap Stop to disconnect").setOngoing(true).addAction(new Notification.Action.Builder(null,"Stop",stop).build()).build();startForeground(50000,notice);if(!running){running=true;worker=new Thread(this::listen,"SoulmateAlerts");worker.start();}return START_STICKY;}
 private String message(){String[] codes={"en","so","ar","ur","hi","bn","fr","es","pt","tr","id","sw","zh"};String[] values={"New activity. Open Muslims Soulmate.","Farriin cusub. Fur Muslims Soulmate.","نشاط جديد. افتح التطبيق.","نئی سرگرمی۔ ایپ کھولیں۔","नई गतिविधि। ऐप खोलें।","নতুন কার্যকলাপ। অ্যাপ খুলুন।","Nouvelle activité. Ouvrez l’application.","Nueva actividad. Abre la aplicación.","Nova atividade. Abra o aplicativo.","Yeni etkinlik. Uygulamayı açın.","Aktivitas baru. Buka aplikasi.","Taarifa mpya. Fungua programu.","有新动态，请打开应用。"};for(int i=0;i<codes.length;i++)if(codes[i].equals(language))return values[i];return values[0];}
 private void listen(){long cursor=getSharedPreferences("alerts",MODE_PRIVATE).getLong("cursor",-1);while(running){try{String cookie=CookieManager.getInstance().getCookie(SITE);if(cookie==null||cookie.isEmpty()){stopSelf();break;}connection=(HttpsURLConnection)new URL(SITE+"/api/events?after="+cursor).openConnection();connection.setInstanceFollowRedirects(false);connection.setConnectTimeout(15000);connection.setReadTimeout(25000);connection.setRequestProperty("Cookie",cookie);connection.setRequestProperty("Accept","text/event-stream");int status=connection.getResponseCode();if(status==401||status==403||(status>=300&&status<400)){stopSelf();break;}if(status!=200)throw new IOException("Unavailable");try(BufferedReader reader=new BufferedReader(new InputStreamReader(connection.getInputStream(),"UTF-8"))){String line;while(running&&(line=reader.readLine())!=null){if(!line.startsWith("data: "))continue;JSONObject data=new JSONObject(line.substring(6));if(data.has("cursor")){cursor=data.getLong("cursor");}else if(data.has("id")){long next=data.getLong("id");if(next>cursor){cursor=next;PendingIntent open=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification n=new Notification.Builder(this,"soulmate_messages").setSmallIcon(android.R.drawable.ic_dialog_email).setContentTitle("Muslims Soulmate").setContentText(message()).setContentIntent(open).setAutoCancel(true).setVisibility(Notification.VISIBILITY_PRIVATE).build();getSystemService(NotificationManager.class).notify((int)(next%40000)+1,n);}}getSharedPreferences("alerts",MODE_PRIVATE).edit().putLong("cursor",cursor).apply();}}}catch(Exception ignored){}finally{if(connection!=null)connection.disconnect();}if(running)try{Thread.sleep(3000);}catch(InterruptedException e){break;}}}
 @Override public void onDestroy(){running=false;if(connection!=null)connection.disconnect();if(worker!=null)worker.interrupt();stopForeground(STOP_FOREGROUND_REMOVE);super.onDestroy();}
}
