import {notifyThread,consumeInquiry,planFor} from '@/lib/features';
import {publicProfile,photoReady} from '@/lib/photo-policy';
import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database,clean,blocked,allowedThread,json,isReviewer} from '@/lib/server';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const user=await getChatGPTUser();if(!user)return json({error:'Sign in to continue.'},401);const db=database(),u=user.userId,now=Date.now();
// Pending inquiries are physically removed when the app is accessed; expired content is never returned.
await db.prepare("DELETE FROM inquiries WHERE status='pending' AND expires<=?").bind(now).run();
const expired=await db.prepare('SELECT id,media FROM posts WHERE expires IS NOT NULL AND expires<=? LIMIT 100').bind(now).all();
for(const p of expired.results){if(p.media&&env.BUCKET)await env.BUCKET.delete(String(p.media));await db.prepare('DELETE FROM posts WHERE id=?').bind(p.id).run();}
const thread=new URL(req.url).searchParams.get('thread');if(thread){if(!await allowedThread(thread,u))return json({error:'This conversation is unavailable.'},403);const rows=await db.prepare('SELECT m.* FROM messages m WHERE thread=? AND NOT EXISTS (SELECT 1 FROM blocks b WHERE (b.owner=? AND b.target=m.sender) OR (b.target=? AND b.owner=m.sender)) ORDER BY created DESC LIMIT 100').bind(thread,u,u).all();const files=(await db.prepare('SELECT id,kind,mime FROM attachments WHERE thread=?').bind(thread).all()).results;return json({messages:rows.results.reverse().map((m:any)=>({...m,attachment:files.find((a:any)=>a.id===m.id)}))});}
const [p,q,g,b,s,r]=await Promise.all([db.prepare('SELECT * FROM profiles WHERE NOT EXISTS (SELECT 1 FROM blocks WHERE (owner=? AND target=profiles.id) OR (target=? AND owner=profiles.id))').bind(u,u).all(),db.prepare('SELECT * FROM inquiries WHERE (sender=? OR recipient=?) AND NOT EXISTS (SELECT 1 FROM blocks WHERE (owner=sender AND target=recipient) OR (owner=recipient AND target=sender))').bind(u,u).all(),db.prepare('SELECT g.*, (SELECT count(*) FROM members WHERE group_id=g.id) AS count, EXISTS(SELECT 1 FROM members WHERE group_id=g.id AND user=?) AS joined FROM groups g').bind(u).all(),db.prepare('SELECT * FROM blocks WHERE owner=?').bind(u).all(),db.prepare("SELECT * FROM posts WHERE (expires IS NULL OR expires>?) AND (status='approved' OR owner=?) AND NOT EXISTS(SELECT 1 FROM blocks WHERE (owner=? AND target=posts.owner) OR (target=? AND owner=posts.owner)) ORDER BY created DESC LIMIT 100").bind(now,u,u,u).all(),db.prepare('SELECT stars FROM ratings WHERE owner=?').bind(u).first()]);
const checks=(await db.prepare('SELECT owner,provider,completed,expires FROM background_checks WHERE expires>?').bind(now).all()).results;const mediaQueue=isReviewer(user)?(await db.prepare("SELECT * FROM posts WHERE status='pending' AND (expires IS NULL OR expires>?)").bind(now).all()).results:[];const photos=(await db.prepare('SELECT * FROM profile_photos').bind().all()).results;const viewerRow:any=p.results.find((x:any)=>x.id===u);const gps=viewerRow?JSON.parse(viewerRow.data).gps:null;return json({user:u,tester:!!user.isTester,mediaQueue,plan:await planFor(u),reviewer:isReviewer(user),reviewQueue:isReviewer(user)?photos.filter((p:any)=>p.status==='pending'&&p.expires>now).map(({media,...p}:any)=>p):[],profiles:p.results.map((x:any)=>({...publicProfile(x,u,gps,photos,now),backgroundCheck:checks.find((c:any)=>c.owner===x.id)||null})),inquiries:q.results,groups:g.results,blocks:b.results,posts:s.results,rating:r?.stars??0});}catch(e){console.error(e);return json({error:'Unable to load your app. Please try again.'},503);}}
export async function POST(req:Request){try{const user=await getChatGPTUser();if(!user)return json({error:'Sign in to continue.'},401);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'Invalid request origin.'},403);const db=database(),u=user.userId,now=Date.now();const a:any=await req.json();const target=typeof a.target==='string'?a.target:'';const id=crypto.randomUUID();
if(a.action==='reviewMedia'){if(!isReviewer(user))return json({error:'Only the owner can review media.'},403);if(!['approved','rejected'].includes(a.status))throw Error('Invalid review.');await db.prepare('UPDATE posts SET status=? WHERE id=?').bind(a.status,target).run();return json({ok:true});}
if(a.action==='language'){const supported=['en','so','ar','ur','hi','bn','fr','es','pt','tr','id','sw','zh'];if(!supported.includes(a.language))throw Error('Choose a supported language.');const row:any=await db.prepare('SELECT data FROM profiles WHERE id=?').bind(u).first();if(!row)throw Error('Create your profile to save your language across devices.');const p=JSON.parse(row.data);p.language=a.language;await db.prepare('UPDATE profiles SET data=?,updated=? WHERE id=?').bind(JSON.stringify(p),now,u).run();return json({ok:true});}
if(a.action==='reviewPhoto'){if(!isReviewer(user))return json({error:'Only the owner can review photos.'},403);if(!['approved','rejected'].includes(a.status))throw new Error('Choose approve or reject.');await db.prepare('UPDATE profile_photos SET status=? WHERE id=? AND expires>?').bind(a.status,target,now).run();return json({ok:true});}
if(a.action==='profile'){const p=a.profile;if(!p || !['Woman','Man'].includes(p.gender) || !['Single','Separated','Married'].includes(p.marital) || !['Never married','Divorced','Widowed','Previously married'].includes(p.past) || !['Growing in faith','Practicing','Very practicing','Prefer to discuss'].includes(p.religiosity))throw new Error('Choose valid profile options.');const age=Number(p.age);if(!Number.isInteger(age)||age<18||age>100||p.agree!==true)throw new Error('You must be 18 or older, Muslim, and accept the community agreement.');const data={name:clean(p.name,80),age,gender:clean(p.gender,30),location:clean(p.location,100),bio:clean(p.bio,1000),religiosity:clean(p.religiosity,60),marital:clean(p.marital,60),past:clean(p.past,60),agree:true,reminders:!!p.reminders,language:['en','so','ar','ur','hi','bn','fr','es','pt','tr','id','sw','zh'].includes(p.language)?p.language:'en',sect:clean(p.sect||'Prefer not to say',60),gps:JSON.parse(String((await db.prepare('SELECT data FROM profiles WHERE id=?').bind(u).first())?.data||'{}')).gps||null};if(data.name.length<2||!data.gender||!data.location)throw new Error('Add your real name, gender, and city or country.');await db.prepare('INSERT INTO profiles(id,data,updated) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated=excluded.updated').bind(u,JSON.stringify(data),now).run();return json({ok:true});}
if(!await db.prepare('SELECT id FROM profiles WHERE id=?').bind(u).first())throw new Error('Create your profile first.');
if(a.action==='gps'){const row:any=await db.prepare('SELECT data FROM profiles WHERE id=?').bind(u).first();const p=JSON.parse(row.data);if(a.enabled===false){p.gps=null;}else{if(a.enabled!==true||typeof a.lat!=='number'||typeof a.lng!=='number'||!Number.isFinite(a.lat)||!Number.isFinite(a.lng)||Math.abs(a.lat)>90||Math.abs(a.lng)>180)throw new Error('Please allow GPS access and try again.');p.gps={lat:Math.round(a.lat*100)/100,lng:Math.round(a.lng*100)/100,updated:now};}await db.prepare('UPDATE profiles SET data=?,updated=? WHERE id=?').bind(JSON.stringify(p),now,u).run();}
else if(a.action==='like'){const photos=(await db.prepare('SELECT * FROM profile_photos WHERE owner=? OR owner=?').bind(u,target).all()).results;if(!photoReady(photos,u,now)||!photoReady(photos,target,now))throw new Error('Both members need current, approved portrait and full-body camera photos before sending Asc.');if(target===u||!await db.prepare('SELECT id FROM profiles WHERE id=?').bind(target).first()||await blocked(u,target))throw new Error('This profile is unavailable.');await db.prepare("DELETE FROM inquiries WHERE status='pending' AND expires<=?").bind(now).run();const prior=await db.prepare('SELECT id FROM inquiries WHERE (sender=? AND recipient=?) OR (sender=? AND recipient=?)').bind(u,target,target,u).first();if(prior)throw new Error('An inquiry or conversation already exists. Check your inbox.');await consumeInquiry(u);await db.prepare("INSERT INTO inquiries VALUES(?,?,?,'pending',?,?)").bind(id,u,target,now,now+48*3600000).run();await db.prepare('INSERT INTO notifications(owner,actor,kind,created) VALUES(?,?,?,?)').bind(target,u,'inquiry',now).run();}
else if(a.action==='reply'){const q:any=await db.prepare("SELECT * FROM inquiries WHERE id=? AND recipient=? AND status='pending' AND expires>?").bind(target,u,now).first();if(!q||await blocked(u,q.sender))throw new Error('This inquiry is no longer available.');if(a.accept){await db.batch([db.prepare("UPDATE inquiries SET status='accepted' WHERE id=?").bind(target),db.prepare('INSERT INTO messages VALUES(?,?,?,?,?)').bind(id,target,q.sender,'Asc',q.created)]);}else await db.prepare('DELETE FROM inquiries WHERE id=?').bind(target).run();}
else if(a.action==='message'){if(!await allowedThread(target,u))throw new Error('This conversation is unavailable.');const body=clean(a.body,2000);if(!body)throw new Error('Write a message first.');await db.prepare('INSERT INTO messages VALUES(?,?,?,?,?)').bind(id,target,u,body,now).run();await notifyThread(target,u,'message');}
else if(a.action==='group'){const name=clean(a.name,80),description=clean(a.description,500);if(name.length<3)throw new Error('Enter a group name.');await db.batch([db.prepare('INSERT INTO groups VALUES(?,?,?,?)').bind(id,u,name,description),db.prepare('INSERT INTO members VALUES(?,?,?)').bind(crypto.randomUUID(),id,u)]);}
else if(a.action==='join'){if(!await db.prepare('SELECT id FROM groups WHERE id=?').bind(target).first())throw new Error('Group not found.');await db.prepare('INSERT OR IGNORE INTO members VALUES(?,?,?)').bind(id,target,u).run();}
else if(a.action==='leave'){await db.prepare('DELETE FROM members WHERE group_id=? AND user=?').bind(target,u).run();}
else if(a.action==='block'){if(target===u)throw new Error('You cannot block yourself.');if(!await db.prepare('SELECT id FROM profiles WHERE id=?').bind(target).first())throw new Error('Profile not found.');await db.prepare('INSERT OR IGNORE INTO blocks VALUES(?,?,?)').bind(id,u,target).run();}
else if(a.action==='unblock'){await db.prepare('DELETE FROM blocks WHERE owner=? AND target=?').bind(u,target).run();}
else if(a.action==='post'){const body=clean(a.body,1000);if(!body)throw new Error('Write your story first.');await db.prepare("INSERT INTO posts VALUES(?,?,'story',?,NULL,'approved',?,?)").bind(id,u,body,now,now+24*3600000).run();}
else if(a.action==='deletePost'){const post:any=await db.prepare('SELECT media FROM posts WHERE id=? AND owner=?').bind(target,u).first();if(post?.media&&env.BUCKET)await env.BUCKET.delete(post.media);await db.prepare('DELETE FROM posts WHERE id=? AND owner=?').bind(target,u).run();}
else if(a.action==='rate'){const n=Number(a.stars);if(!Number.isInteger(n)||n<1||n>5)throw new Error('Choose 1 to 5 stars.');await db.prepare('INSERT INTO ratings VALUES(?,?) ON CONFLICT(owner) DO UPDATE SET stars=excluded.stars').bind(u,n).run();}
else if(a.action==='report'){const reason=clean(a.reason,1000);if(!reason)throw new Error('Please explain what happened.');await db.prepare('INSERT INTO reports VALUES(?,?,?,?,?)').bind(id,u,target,reason,now).run();}
else throw new Error('Unknown action.');return json({ok:true});
}catch(e){return json({error:e instanceof Error?e.message:'Unable to save. Please try again.'},400);}}
